update registerhandling to use i1* pointer
Quantinuum/pytket-qir pull request #61
Opened 2023-08-07 09:32 UTC by cqc-melf

2023-08-08 16:25 UTC, cqc-melf commented
The discussed changes for the classical register handling

2023-08-08 17:27 UTC, qartik requested changes
I think we talked about settling on better names for the API functions. I have left some suggestions. Perhaps it makes sense to list them out all together:

```llvm
i1*  create_creg      (i64 size                     )
void set_creg_to_int  (i1* creg, i64 value          )
i64  get_int_from_creg(i1* creg                     )
void set_creg_bit     (i1* creg, i64 index, i1 value)
i1   get_creg_bit     (i1* creg, i64 index          )
```

Note that in the backend compiler, a notion of `creg` is prevalent so perhaps it makes sense to also use it for this API.

I am open to hear about other suggestions. cc: @peter-campora

2023-08-08 17:27 UTC, qartik commented on pytket/qir/conversion/conversion.py
> +        # i1 read_bit_from_reg(i1* reg, i64 index)
```suggestion
        # i1 get_creg_bit(i1* creg, i64 index)
```

2023-08-08 17:27 UTC, qartik commented on pytket/qir/conversion/conversion.py
> +        # void set_one_bit_in_reg(i1* reg, i64 index, i1 value)
```suggestion
        # void set_creg_bit(i1* creg, i64 index, i1 value)
```

2023-08-08 17:27 UTC, qartik commented on pytket/qir/conversion/conversion.py
> +        # void set_all_bits_in_reg(i1* reg, i64 value)
```suggestion
        # void set_creg_to_int(i1* creg, i64 value)
```

2023-08-08 17:27 UTC, qartik commented on pytket/qir/conversion/conversion.py
> +        # i1* create_reg(i64 size)
```suggestion
        # i1* create_creg(i64 size)
```

2023-08-08 17:27 UTC, qartik commented on pytket/qir/conversion/conversion.py
> +        # i64 create_reg(i1* reg)
```suggestion
        # i64 get_int_from_creg(i1* creg)
```
Specifically `read_all_bits_from_reg` could be better called `get_int_from_creg`

2023-08-09 06:52 UTC, cqc-melf commented
> I think we talked about settling on better names for the API functions. I have left some suggestions. Perhaps it makes sense to list them out all together:
> 
> ```llvm
> i1*  create_creg      (i64 size                     )
> void set_creg_to_int  (i1* creg, i64 value          )
> i64  get_int_from_creg(i1* creg                     )
> void set_creg_bit     (i1* creg, i64 index, i1 value)
> i1   get_creg_bit     (i1* creg, i64 index          )
> ```
> 
> Note that in the backend compiler, a notion of `creg` is prevalent so perhaps it makes sense to also use it for this API.
> 
> I am open to hear about other suggestions. cc: @peter-campora

I have done a search and replace as suggested, I have replaced that in all of the ll files for the tests as well.

See @cqc-melf
[rename functions as suggested](https://github.com/CQCL/pytket-qir/pull/61/commits/867e2a8f511d225eee6a99b4efcbb942a1c69897)
[867e2a8](https://github.com/CQCL/pytket-qir/pull/61/commits/867e2a8f511d225eee6a99b4efcbb942a1c69897)

And @cqc-melf
[rename reg to creg in comments](https://github.com/CQCL/pytket-qir/pull/61/commits/3a4cfdd32210724451ec9f7b5e4dabb7a6ee64b8)
[3a4cfdd](https://github.com/CQCL/pytket-qir/pull/61/commits/3a4cfdd32210724451ec9f7b5e4dabb7a6ee64b8)

2023-08-09 07:56 UTC, cqc-alec approved these changes

2023-08-09 12:23 UTC, qartik approved these changes
Thanks for the careful changes!

2023-08-09 13:20 UTC, merged